steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/jai-kissan-backend:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/jai-kissan-backend:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'jai-kissan-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/jai-kissan-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'PYTHONPATH=/app,CHROMA_DB_IMPL=duckdb+parquet,PERSIST_DIRECTORY=/app/agri_chromadb'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/jai-kissan-backend:$COMMIT_SHA'

# Timeout for the entire build
timeout: '1200s'
